In [2]:
import numpy as np

In [ ]:
import sys
python_list = list(range(100))

print(sys.getsizeof(python_list[0])*len(python_list))
numpy_array = np.arange(100)
print(numpy_array.nbytes)

In [ ]:
l1 = [1, 2, 3]
l2 = [8, 7, 9]

tuple(zip(l1, l2))

for x, y in zip(l1, l2):
    print(x, y)

In [ ]:
import time
size = 1000000

l1 = list(range(size))
l2 = list(range(size))

start_time = time.time()
l3 = [x+y for x, y in zip(l1, l2)]
end_time = time.time()

print(l3[:10])

print("Tempo de execução da python lista: ", end_time - start_time)

n1 = np.arange(size)
n2 = np.arange(size)
start_time = time.time()
n3 = n1 + n2
end_time = time.time()

print(n3[:10])

print("Tempo de execução de numpy: ", end_time - start_time)

In [ ]:
#Segunda aula https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/2187

rev_q1 = np.array([10, 12, 9])
print(rev_q1.ndim)

rev = np.array([[10, 12, 9], [15, 11, 13]])
print(rev.ndim)

print(rev[1, 2])

rev[1, 2] = 14

In [ ]:
rev = np.array(
 [[10, 12, 9],
 [15, 11, 13]], dtype=np.float64)

print(rev.dtype)
#tamanho de byte ocupado por cada elemento
print(rev.itemsize)
print(rev.size)
print(rev.shape)

np.sort(rev, axis=None)

zerosArray = np.zeros((2, 3))
onesArray = np.ones((2, 3))
print(zerosArray, onesArray)

In [ ]:
np_arange = np.arange(20, 30, 2)
array_linspace = np.linspace(10, 20, 5)
print(np_arange, array_linspace)

new_rev = rev.ravel()
new_rev2 = rev.flatten()

print(new_rev2)

rev_new = rev.reshape(3, 2)
print(rev_new)

print(rev.max(), rev.min())

In [ ]:
rev = np.array(
 [[10, 12, 9],
 [15, 11, 13]], dtype=np.float64)
print(rev.sum(axis=1))

for r in rev:
  print("row => ", r)

In [ ]:
b = np.array([1, 4, 16])

arr_sqrt = np.sqrt(b)
arr_square = np.square(b)

print(arr_square)

In [ ]:
#Terceira aula https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/2188

#Sales data for Quarter 1 (Matrix 1)
#Rows represent different products, columns represent different regions

q1 = np.array([
    [200, 220, 250], #Product A
    [150, 180, 210], #Product B
    [300, 330, 360]  #Product C
])

q2 = np.array([
    [209, 231, 259], #Product A
    [155, 192, 222], #Product B
    [310, 340, 375]  #Product C
])

count1 = q1 + q2
count2 = q2 - q1

print(count2)

#porcentagem calc
porcent = (q2-q1)*100/q1
print(porcent)

In [ ]:
prices = np.array([
    [10, 12, 11], #Prices for Product A in different regions
    [8, 9, 10], #Prices for product B
    [15, 16, 17], #Prices for Product C
])

q1_revenue = q1 * prices
#print(q1_revenue)

q1_discounts = q1_revenue * 0.2
q1_discounts

net_revenue = q1_revenue - q1_discounts
print(net_revenue)

sum_discount = np.sum(q1_discounts)
print(sum_discount)

sum_revenue = np.sum(net_revenue)
print(sum_revenue)

In [ ]:
features = np.array([
    [2000, 3], # house 1
    [1800, 2] # house 2
])

weights = np.array([150, 50000])

#Dot product of house 1
2000*150 + 3*50000

dot_product = np.dot(features, weights)
print(dot_product)

[450000 370000]

In [ ]:
c = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.cross(c, b)

array([-3,  6, -3])

In [ ]:
#Quarta aula https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/2189

a = np.array([6, 7, 8, 9])
a[0:2]
a[2:]
a[-1]
a[-3:]

In [ ]:
b = np.array([
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

b[1, 2]
b[2, 0]

b[-1, 0:2]
primeira_col = b[:, 0:1]
segunda_col = b[:, 1:2]
terceira_col = b[:, 2:]
sec_to_third = b[:, 1:3]


print(primeira_col)
print(segunda_col)
print(terceira_col)
print(sec_to_third)

In [ ]:
# Customer ID, name

a = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Custumer Id, purchase amount, purchase date
b = np.array(
    [
      [101, 250.50, '2023-08-01'],
      [102, 150.00, '2023-08-02'],
      [103, 300.75, '2023-08-01'],
    ]
)

c = np.hstack((a, b))
print(c)

d = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

e = np.vstack((a, d))
print(e)

In [ ]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

a, b = np.hsplit(transactions, [3])
print(a)
print(b)

In [ ]:
a, b = np.vsplit(transactions, [3])
print(a)
print()
print(b)

In [ ]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
print(result)
arr_res = monthly_sales[result]
print(arr_res)

month_sell_max = np.argmax(monthly_sales)
print(month_sell_max)

In [ ]:
segunda_col = transactions[:, 2].astype(float)

t_index = np.argmax(segunda_col)
print(transactions[t_index])

ids = transactions[:, 0]
print(ids)
print(transactions[transactions[:,0]=='102'])

['104' 'David' '400.2' '2023-08-03']
['101' '102' '103' '104' '105']
[['102' 'Bob' '150.0' '2023-08-02']]

In [4]:
#chapter 5 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1540
import pandas as pd
import csv

In [ ]:
#Sem usar pandas
def calc_rat_stats(data, industry=None):
  ratings = []
  for row in data:
    if row[3] != 'NULL' and (not industry or row[1] == industry):
      ratings.append(float(row[3]))
  max_rating = max(ratings)
  min_rating = min(ratings)
  avg_rating = sum(ratings) / len(ratings)
  return max_rating, min_rating, avg_rating

with open("movies.csv") as f:
  data = list(csv.reader(f))
  header = data[0]
  data = data[1:]

  max_rating, min_rating, avg_rating = calc_rat_stats(data)
  print(f"All records: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")

  max_rating, min_rating, avg_rating = calc_rat_stats(data, industry='Bollywood')
  print(f"Bollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")

  max_rating, min_rating, avg_rating = calc_rat_stats(data, industry='Hollywood')
  print(f"Hollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")

In [ ]:
df = pd.read_csv("movies.csv")
# print(df.head(7))
# print(df.tail(4))
# print(df.sample(3))
# print(df[2:6])
# print(df.shape)

In [ ]:
#Com pandas
print(df['imdb_rating'].min(), df['imdb_rating'].max(), df['imdb_rating'].mean())

df_bollywood = df[df['industry'] == 'Bollywood']
df_hollywood = df[df['industry'] == 'Hollywood']

print(df_bollywood['imdb_rating'].min(), df_bollywood['imdb_rating'].max(), df_bollywood['imdb_rating'].mean())
print(df_hollywood['imdb_rating'].min(), df_hollywood['imdb_rating'].max(), df_hollywood['imdb_rating'].mean())

In [ ]:
#Aula 2 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1541
df.head(3)
df.columns
df['industry'].unique()
df['language'].unique()
df['industry'].value_counts()

In [ ]:
#How many movies are there for each of these languages
df_bengali = df[df['language'] == 'Bengali']
print("Bengali: ", df_bengali['title'].count())

df_eng = df[df['language'] == 'English']
print("English: ", df_eng['title'].count())

df_hindi = df[df['language'] == 'Hindi']
print("Hindi: ", df_hindi['title'].count())

df_kann = df[df['language'] == 'Kannada']
print("Kannada: ", df_kann['title'].count())

df_tel = df[df['language'] == 'Telugu']
print("Telugu: ", df_tel['title'].count())

#ou

df['language'].value_counts()

In [ ]:
new_df = df[["title", "imdb_rating", "industry"]]
new_df

In [ ]:
df[(df['release_year'] >= 2000) & (df['release_year'] <= 2010)]

In [ ]:
df.studio.unique()
df[df['studio'] == "Marvel Studios"]

In [ ]:
df.describe()
df.info()

In [ ]:
df[(df['imdb_rating'] == df['imdb_rating'].max()) | (df['imdb_rating'] == df['imdb_rating'].min())]

In [ ]:
#Versão mostrada na aula:
df["age"] = df['release_year'].apply(lambda x: 2026 - x)
df["profit"] = df.apply(lambda x: x['revenue'] - x['budget'], axis=1)
df.head(5)

In [ ]:
#Minha versão:
df["age"] = 2026 - df['release_year']
df['profit'] = df['revenue'] - df['budget']
df.head(5)


Para operações simples como esta, SEMPRE use a abordagem vetorizada (versão 1).
O apply() só deve ser usado como último recurso para operações que não podem ser vetorizadas.

In [ ]:
df.index
df.set_index("title", inplace=True)

In [ ]:
df.index
df.head(3)

In [ ]:
df.loc["Pather Panchali"]

In [ ]:
df.loc[["Pather Panchali", "Doctor Strange in the Multiverse of Madness"]]

In [ ]:
df.iloc[2:6]

In [ ]:
df.reset_index(inplace=True)
df.head()

In [ ]:
#Exercicio
df = pd.read_csv("bengaluru_house_prices.csv")

print("Df number of columns and rows: ")
print(df.shape)
print("\nDf original:")
print(df.head(5))
print("\nDf area_type: ")
print(df['area_type'].unique())
print("\nDf size: ")
print(df['size'].unique())

"""
- Filter data which have **'2 BHK'** house size and area_type of **'Super built-up  Area'**
- Also get the count of such rows
"""

df_new = df[(df['size'] == '2 BHK') & (df['area_type'] == 'Super built-up  Area')]
print("\nDf filtered shape: ")
print(df_new.shape[0])
df['price_category'] = df['price'].apply(lambda x: 'Affordable' if x < 80 else 'High cost')
print("\nDf filtered: ")
print(df.head(5))

print("\nDf who are greater than the mean: ")
mean = df['price'].mean()
df_greater = df[df['price'] > mean]
print(df_greater)

In [ ]:
#Aula 3 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1542

df_without_skip = pd.read_csv("stock_data.csv")
print(df_without_skip, end="\n\n")

#skiprows = skip a given number of rows
df_skip = pd.read_csv("stock_data.csv", skiprows=1)
print(df_skip, end="\n\n")

#another way of doing the same thing, but using "header" parameter
df_header = pd.read_csv("stock_data.csv", header=1)
print(df_header, end="\n\n")

df_name_col = pd.read_csv("stock_data.csv", header=1, names=["stock_symbol", "eps", "revenue", "price", "people"])
print("df_name_col\n")
print(df_name_col, end="\n\n")

df_nrows = pd.read_csv("stock_data.csv", header=1, nrows=2)
print(df_nrows, end="\n\n")

In [ ]:
df_navalues = pd.read_csv("stock_data.csv", header=1, na_values={
    'eps': ['not available'],
    'revenue': [-1],
    'people': ['not available', 'n.a.'],
    'price': ['n.a.']
})
df_navalues

In [ ]:
df = pd.read_csv("stock_data.csv", header=1, na_values=['not available', -1, 'n.a.'])
df

In [ ]:
df["pe"] = df["price"]/df["eps"]
df

In [ ]:
df.to_csv("pe.csv", index=False)
df.to_csv("pe1.csv", index=False, header=False)

In [ ]:
#Reading Excel files
df_movies = pd.read_excel("movies_db.xlsx", "movies")
df_movies.head(4)

In [ ]:
df_financials = pd.read_excel("movies_db.xlsx", "financials")
df_financials.head(4)

In [ ]:
def standardize_currency(curr):
  if curr == "$$" or curr == "Dollars":
    return "USD"
  return curr

df_financials = pd.read_excel("movies_db.xlsx", "financials", converters={
    'currency': standardize_currency
})
df_financials.head(4)

In [ ]:
df_merged = pd.merge(df_movies, df_financials, on="movie_id")
df_merged

In [ ]:
df_merged.to_excel("movies_merged.xlsx", sheet_name="merged", index=False)

In [ ]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})
df_stocks

In [ ]:
df_weather = pd.DataFrame({
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'event' : ['Rain', 'Sunny', 'Snow']
    })
df_weather

In [ ]:
#Create an excel file named "stocks_weather.xlsx" with 2 sheets, one called "stocks", the other called "weather"
with pd.ExcelWriter("stocks_weather.xlsx") as writer:
  df_stocks.to_excel(writer, sheet_name="stocks")
  df_weather.to_excel(writer, sheet_name="weather")

In [ ]:
#Exercise
#First read the csv and show top5 rows
df_movies_data = pd.read_csv("movies_data.csv")
df_movies_data.head(5)

In [ ]:
#Second add new col "year_classify"
df_movies_data["year_classify"] = df_movies_data["release_year"].apply(lambda x: "before 2000" if x < 2000 else "from 2000")
df_movies_data.head(2)

In [ ]:
#course solution
df_movies_data['year_classify'] = df_movies_data.apply(lambda x: 'Before 2000' if x['release_year'] < 2000 else 'From 2000', axis=1)
df_movies_data.head(2)

In [ ]:
#Third: save the above dataframe with the name "final_movie_data.csv"
df_movies_data.to_csv("final_movie_data.csv", index=False)
#course solution
df.to_csv('final_movie_data.csv', columns=['movie_id', 'title', 'budget', 'revenue', 'year_classify'], index = False)

In [ ]:
#https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1543
df_weather = pd.read_csv("weather_data.csv", parse_dates=["day"])
df_weather

In [ ]:
df_weather.set_index('day', inplace=True)
df_weather

In [ ]:
df_weather.fillna(0)

In [ ]:
new_test = df_weather.fillna({
    'temperature': df_weather["temperature"].mean(),
    'windspeed': df_weather["windspeed"].mean(),
    'event': 'No Event'
})

new_test

In [ ]:
df_weather.fillna(method='ffill')

In [ ]:
df_weather.fillna(method='bfill', axis='columns')

In [ ]:
df_weather.fillna(method='ffill', limit=2)

In [ ]:
df_weather.interpolate()

In [ ]:
df_weather.dropna()

In [ ]:
df_weather.dropna(how='all')

In [ ]:
df_weather.dropna(thresh=2)

In [ ]:
df_weather.dropna(thresh=1)

In [ ]:
df_weather

In [ ]:
#Exercise
#Q1
fruits_data = pd.read_csv("fruits_data.csv")
print("Rows and Cols", fruits_data.shape)
print("All Cols", fruits_data.columns)
print(fruits_data)

In [ ]:
#Q2
new_df = fruits_data.fillna(-1)
new_df

In [ ]:
#Q3
new_df = fruits_data.fillna({
    'apple(1kg)': fruits_data['apple(1kg)'].mean(),
    'banana(1 dozen)': fruits_data['banana(1 dozen)'].mean(),
    'grapes(1kg)': fruits_data['grapes(1kg)'].median(),
    'mango(1kg)': fruits_data['mango(1kg)'].median(),
    'Water Melons(1)': 'Not Available'
})
new_df

In [ ]:
#Q4
new_df = fruits_data.fillna(method='ffill')
print(new_df)
#Q5
df_thre = fruits_data.dropna(thresh=4)
print(df_thre)

In [ ]:
#Q6
final_df = fruits_data.dropna()
final_df

In [ ]:
fruits_data

In [ ]:
#Aula 5 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1544
df_weather_data = pd.read_csv("weather_data.csv")
df_weather_data

In [ ]:
df_weather_data.replace([-99999, -88888], np.nan)
# or: df_weather_data.replace(to_replace=[-99999, -88888], value=np.nan)

In [ ]:
df_weather_data.replace({
    'temperature': -99999,
    'windspeed': [-99999, -88888],
    'event': 'no event'
}, np.nan)

In [ ]:
df_weather_data.replace({
    -99999: np.nan,
    -88888: np.nan,
    'no event': 'Sunny'
})

In [ ]:
data_frame = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})

data_frame.replace(set([x for x in data_frame['score'].values]), [1, 2, 3, 4])
#or data_frame.replace(['poor', 'average', 'good', 'exceptional'], [1, 2, 3, 4])

In [ ]:
#Exercise
#Q1
df = pd.read_csv("food_db.csv")
print(df.shape)
df

In [ ]:
#Q3
df.replace(["5%", "10%"], "13%")
df

In [ ]:
#Q4
#new_df = df.replace(set([x for x in df['rating'].values]), [2, 1, 4, 3])
new_df = df.replace(['Excellent', 'Very Good', 'Good', 'Average'], [4, 3, 2, 1])
new_df

In [42]:
#Aula 6 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1545
city_weathers = pd.read_csv("weather_by_cities.csv")
city_weathers

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [ ]:
city_weathers[city_weathers['city'] == 'new york'].temperature.max()

In [ ]:
g = city_weathers.groupby('city')
g

In [ ]:
for city, data in g:
  print(city, end="\n\n")
  print(data, end="\n\n")
  print("Max: ", data.temperature.max(), end="\n=============\n")

print("\nMean values: \n")
for city, data in g:
  print(city, end="\n\n")
  print(data, end="\n\n")
  print("Max: ", data.temperature.mean(), end="\n=============\n")

In [ ]:
print(g.get_group("paris"))
print("===========")
print(g.get_group("mumbai"))
print("===========")
print(g.get_group("new york"))
print("==========")

print(g.max())
print(g.min())
print("\n==========\n")
print(g.describe())

In [ ]:
def grouper(df, idx, col):
  if 80 <= df[col].loc[idx] <= 90:
    return '80-90'
  elif 50 <= df[col].loc[idx] <= 60:
    return '50-60'
  else:
    return 'others'

In [ ]:
g = city_weathers.groupby(lambda idx: grouper(city_weathers, idx, 'temperature'))
g

In [ ]:
for key, d in g:
  print("Key:", key)
  print("Data:", d)

In [ ]:
#Exercise
#Q1
movies_df = pd.read_csv("movies_data.csv")
movies_df

In [ ]:
g = movies_df.groupby("industry")
print(g.size())
print(g.get_group("Bollywood"))

In [47]:
def group(df, idx, col):
  if df[col].loc[idx] <= 3.9:
    return 'Poor'
  elif df[col].loc[idx] <= 7.9:
    return 'Average'
  else:
    return 'Good'

#solution
def grouper2(df, idx, col):
    '''
        This function returns category based on imdb_rating
    '''
    if 1 <= df[col].loc[idx] <= 3.9:
        return 'Poor'
    elif 4 <= df[col].loc[idx] <= 7.9:
        return 'Average'
    elif 8 <= df[col].loc[idx] <= 10:
        return 'Good'
    else:
        return "others"

In [ ]:
g = movies_df.groupby(lambda x: grouper2(movies_df, x, 'imdb_rating'))
print(g.size())

for k, v in g:
  print(k)
  print(v)

In [ ]:
#Aula 7 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1546

india_weather = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 45, 30],
    "humidity": [80, 60, 78]
})

india_weather

In [ ]:
us_weather = pd.DataFrame({
    "city": ["new york", "chicago", "orlando"],
    "temperature": [21, 14, 35],
    "humidity": [68, 65, 75]
})
us_weather

In [ ]:
df = pd.concat([india_weather, us_weather])
df

In [ ]:
df = pd.concat([india_weather, us_weather], ignore_index=True)
df

In [ ]:
df = pd.concat([india_weather, us_weather], keys=["india", "us"])
df.loc["us"]["temperature"]

In [ ]:
temp_df = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 45, 30]
}, index=[0, 1, 2])
temp_df

In [ ]:
windspeed_df = pd.DataFrame({
    "city": ["delhi", "mumbai"],
    "windspeed": [7, 12],
}, index=[1, 0])

windspeed_df

In [ ]:
pd.concat([temp_df, windspeed_df], axis=1)

       city  temperature    city  windspeed
0    mumbai           32   delhi        7.0
1     delhi           45  mumbai       12.0
2  banglore           30     NaN        NaN

In [ ]:
df1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando"],
    "temperature": [21, 14, 35]
})

df1

In [ ]:
df2 = pd.DataFrame({
    "city": ["chicago", "new york", "orlando"],
    "humidity": [65, 68, 75]
})

df2

In [ ]:
d3 = pd.merge(df1, df2, on="city")
d3

In [ ]:
df_1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando", "baltimore"],
    "temperature": [21, 14, 35, 38]
})

df_1

In [ ]:
df_2 = pd.DataFrame({
    "city": ["chicago", "new york", "san francisco"],
    "humidity": [65, 68, 71]
})
df_2

In [ ]:
df_3 = pd.merge(df_1, df_2, on="city", how="inner")
df_3

In [ ]:
df_3 = pd.merge(df_1, df_2, on="city", how="left")
df_3

In [ ]:
df_3 = pd.merge(df_1, df_2, on="city", how="right")
df_3

In [ ]:
df_3 = pd.merge(df_1, df_2, on="city", how="outer")
df_3

In [ ]:
#Exercicio
#Q1

df_financials = pd.read_csv("financials.csv")

df_languages = pd.read_csv("languages.csv")

df_movies = pd.read_csv("movies.csv")

In [ ]:
df_financials.head(3)

In [ ]:
df_languages.head(3)

In [ ]:
df_movies.head(3)

In [ ]:
#Q2
df_new_movies = pd.read_csv("new_movies.csv")
df_new_movies

In [ ]:
df_movies = pd.concat([df_movies, df_new_movies], ignore_index=True)
df_movies.tail(5)

In [ ]:
#Q3
df_movies = pd.merge(df_movies, df_languages, on="language_id", how="inner")
df_movies.head(5)

In [ ]:
#Q4
df_movies = pd.merge(df_movies, df_financials, on="movie_id", how="left")
df_movies.head(5)

In [ ]:
#Q5

final_df = df_movies[['movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency']]

final_df.to_csv("final_complete_data.csv", index=False)

#Solution:
df_movies.to_csv('final_complete_data2.csv', columns = ['movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency'],
                 index = False)

In [1]:
#Aula 8 https://codebasics.io/courses/math-and-statistics-for-data-science/lecture/1547
import matplotlib.pyplot as plt

In [53]:
df_sales = pd.read_excel("linechart.xlsx")
df_sales.head()

df_sales.rename(columns={'Washing Machine': 'WM'}, inplace=True)
df_sales

   Quarter  Fridge  Dishwasher   WM
0  Q1 2022    12.5         8.0  9.2
1  Q2 2022    11.0         7.5  8.5
2  Q3 2022    13.2         9.0  7.5
3  Q4 2022    16.4        11.0  7.6
4  Q1 2023    13.8         9.5  6.8
5  Q2 2023    14.0         8.0  6.0

In [ ]:

plt.figure(figsize=(12, 4))
plt.plot(df_sales["Quarter"], df_sales["Fridge"], color="blue", label="Fridge")
plt.plot(df_sales["Quarter"], df_sales["Dishwasher"], color="red", label="Dishwasher")
plt.plot(df_sales["Quarter"], df_sales["WM"], color="yellow", label="Washing Machine")

plt.title("Product Sales")
plt.xlabel("Revenue (min $)")
plt.ylabel("Quarter")
plt.legend()
plt.show()

In [ ]:
total_sales = df_sales[["Fridge", "Dishwasher", "WM"]].sum()
total_sales.index

Index(['Fridge', 'Dishwasher', 'WM'], dtype='object')

In [ ]:
plt.pie(total_sales, labels=total_sales.index, autopct="%1.1f%%", explode=(0.1, 0, 0), shadow=True, startangle=90)
#same as: plt.pie(total_sales, labels=['Fridge', 'Dishwasher', 'WM'])
plt.show()

In [ ]:
df_sales.plot(kind="bar", x="Quarter")

plt.xticks(rotation=45)
plt.show()

In [ ]:
df_change = df_sales.set_index("Quarter")

In [ ]:
df_change.loc["Q1 2022"]

Fridge        12.5
Dishwasher     8.0
WM             9.2
Name: Q1 2022, dtype: float64

In [ ]:
df_change.plot(kind="bar")

plt.xticks(rotation=45)
plt.show()

In [ ]:
df_score = pd.read_excel("histograms.xlsx")
df_score.head(3)

In [3]:
import seaborn as sns

In [ ]:
sns.histplot(df_score["Exam_Score"], kde=True)

plt.xlabel("Score")
plt.ylabel("Count")
plt.title("Exam Score")
plt.show()

In [ ]:
sns.histplot(data=df_score, x="Exam_Score", kde=True)

plt.xlabel("Score")
plt.ylabel("Count")
plt.title("Exam Score")
plt.show()

In [ ]:
plt.hist(df_score["Exam_Score"])

In [ ]:
df_scatter = pd.read_excel("scatter_plot.xlsx")
df_scatter

In [ ]:
sns.scatterplot(data=df_scatter, x="area_square_ft", y="price")

In [ ]:
x=np.arange(1, 20, 2)
y = np.array([x*2 for x in x])

data = x
df_n = pd.DataFrame(data, columns=["data"])

sns.scatterplot(data=df_n, x=x, y=y)
plt.plot(x, y)

In [ ]:
x = np.array([np.linspace(1, 20, 5), np.linspace(20, 30, 5), np.linspace(31, 50, 5), np.linspace(51, 100, 5)])
print(x)
print("Primeira coluna: ", x[:,0])
print("Segunda coluna: ", x[:,1])
print("Terceira coluna: ", x[:,2])
print("Quarta coluna: ", x[:,3])
print("Quinta coluna: ", x[:,4])

In [ ]:
x = np.array([np.linspace(1, 20, 5), np.linspace(20, 30, 5), np.linspace(31, 50, 5), np.linspace(51, 70, 5), np.linspace(71, 90, 5), np.linspace(91, 110, 5)])
print(x)
y = np.array([np.linspace(31, 50, 5), np.linspace(51, 100, 5), np.linspace(51, 70, 5), np.linspace(71, 90, 5), np.linspace(91, 110, 5), np.linspace(111, 130, 5)])
data = pd.DataFrame(x)
sns.scatterplot(data=data, x=x[:,0], y=y[:,0])
plt.plot(x[:,0], y[:,0])
plt.show()